export const articles = [
	{
		"title": "Lorem ipsum dolor sit amet",
		"slug": "lorem-ipsum",
		"description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce commodo erat vel ante convallis, sit amet interdum nulla sollicitudin. Aliquam sit amet ornare lectus, eu hendrerit nisi",
		"content": "<h2>Lorem ipsum dolor sit amet</h2><p>Consectetur adipiscing elit. Curabitur commodo libero sit amet maximus dictum. Aenean cursus, tellus eget venenatis laoreet, eros sem mollis lectus, fermentum egestas tellus nibh vitae tellus. Nullam eget mi posuere, pellentesque tellus id, elementum risus. Sed cursus tempus convallis. Nulla quis interdum nulla. Nulla suscipit neque eget tempus dictum. In a elit vitae mi sollicitudin malesuada sit amet at neque. Ut mi sem, efficitur ac suscipit et, pellentesque ut velit. Pellentesque lorem lacus, maximus id scelerisque ut, vehicula non ex. Proin auctor orci a rutrum fermentum. Vivamus ut molestie velit. Morbi viverra orci ut risus iaculis, vel varius nisl aliquet.&nbsp;</p><p>Donec velit nisl, cursus quis lectus a, posuere viverra tellus. Nam vitae suscipit dolor. Morbi sed mauris vitae eros euismod euismod. Donec et massa ut nibh porta rhoncus a a dolor. Nulla facilisi. Pellentesque posuere aliquet bibendum. Cras porta mi nec augue fermentum pharetra. Nunc cursus, mauris ac pharetra bibendum, purus massa sodales neque, a elementum nisi purus vel risus. Nullam eu lorem commodo, ornare dolor commodo, tincidunt risus. Morbi sed eros sed metus mollis tristique at non ex. Vivamus sed euismod leo. Mauris vitae magna non erat placerat suscipit. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Morbi gravida rutrum leo quis tempor.&nbsp;</p><p>Nullam eleifend nisi quis turpis imperdiet placerat. Phasellus vitae urna quis eros posuere tincidunt. Praesent pretium mauris ex, vitae ornare nisi posuere pretium. Maecenas sollicitudin hendrerit viverra. Morbi ac condimentum nibh, viverra tempus diam. Fusce placerat scelerisque bibendum. Ut ullamcorper ac mi et iaculis. Pellentesque non viverra dolor, vitae tincidunt enim. Integer tempus in nibh id maximus. Sed ac nisl purus. Duis porttitor aliquet urna vel vestibulum. Nulla tempus dignissim ligula, sed sollicitudin sem euismod non. Donec aliquet mauris porttitor eleifend aliquam. Sed turpis metus, condimentum et accumsan non, facilisis id risus. Donec erat justo, tincidunt sed turpis congue, tincidunt luctus dolor. Aenean aliquam nulla nec leo viverra luctus. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Suspendisse feugiat quis tellus et maximus.&nbsp;</p><p>Proin placerat justo velit, vitae ultricies nunc imperdiet eu. Aliquam iaculis ante quis magna rhoncus, sit amet ornare libero gravida. Praesent porta ultricies libero, at imperdiet arcu imperdiet quis. Pellentesque in arcu dui. Curabitur in lectus eget neque efficitur sollicitudin id vitae nulla. Vivamus mi erat, porttitor ac magna in, vehicula rutrum turpis. Sed porta non nunc a malesuada. Cras et auctor purus.</p>",
		"cover": {
			"data": {
				"attributes": {
					"width": 1920,
					"height": 1279,
					"url": "/yifu-wu-NZDaOY-VZGY-unsplash.jpg",
				}
			}
		},
	},
	{
		"title": "Fusce commodo erat vel ante convallis",
		"slug": "fusce-commodo",
		"description": "Etiam ornare dolor a dolor ultrices euismod eu nec risus. Nunc tempus iaculis finibus. Suspendisse facilisis venenatis sapien, sed malesuada mi vulputate et. Maecenas ornare non velit sed pellentesque.",
		"content": "<h2>Lorem ipsum dolor sit amet</h2><p>Consectetur adipiscing elit. Curabitur commodo libero sit amet maximus dictum. Aenean cursus, tellus eget venenatis laoreet, eros sem mollis lectus, fermentum egestas tellus nibh vitae tellus. Nullam eget mi posuere, pellentesque tellus id, elementum risus. Sed cursus tempus convallis. Nulla quis interdum nulla. Nulla suscipit neque eget tempus dictum. In a elit vitae mi sollicitudin malesuada sit amet at neque. Ut mi sem, efficitur ac suscipit et, pellentesque ut velit. Pellentesque lorem lacus, maximus id scelerisque ut, vehicula non ex. Proin auctor orci a rutrum fermentum. Vivamus ut molestie velit. Morbi viverra orci ut risus iaculis, vel varius nisl aliquet.&nbsp;</p><p>Donec velit nisl, cursus quis lectus a, posuere viverra tellus. Nam vitae suscipit dolor. Morbi sed mauris vitae eros euismod euismod. Donec et massa ut nibh porta rhoncus a a dolor. Nulla facilisi. Pellentesque posuere aliquet bibendum. Cras porta mi nec augue fermentum pharetra. Nunc cursus, mauris ac pharetra bibendum, purus massa sodales neque, a elementum nisi purus vel risus. Nullam eu lorem commodo, ornare dolor commodo, tincidunt risus. Morbi sed eros sed metus mollis tristique at non ex. Vivamus sed euismod leo. Mauris vitae magna non erat placerat suscipit. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Morbi gravida rutrum leo quis tempor.&nbsp;</p><p>Nullam eleifend nisi quis turpis imperdiet placerat. Phasellus vitae urna quis eros posuere tincidunt. Praesent pretium mauris ex, vitae ornare nisi posuere pretium. Maecenas sollicitudin hendrerit viverra. Morbi ac condimentum nibh, viverra tempus diam. Fusce placerat scelerisque bibendum. Ut ullamcorper ac mi et iaculis. Pellentesque non viverra dolor, vitae tincidunt enim. Integer tempus in nibh id maximus. Sed ac nisl purus. Duis porttitor aliquet urna vel vestibulum. Nulla tempus dignissim ligula, sed sollicitudin sem euismod non. Donec aliquet mauris porttitor eleifend aliquam. Sed turpis metus, condimentum et accumsan non, facilisis id risus. Donec erat justo, tincidunt sed turpis congue, tincidunt luctus dolor. Aenean aliquam nulla nec leo viverra luctus. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Suspendisse feugiat quis tellus et maximus.&nbsp;</p><p>Proin placerat justo velit, vitae ultricies nunc imperdiet eu. Aliquam iaculis ante quis magna rhoncus, sit amet ornare libero gravida. Praesent porta ultricies libero, at imperdiet arcu imperdiet quis. Pellentesque in arcu dui. Curabitur in lectus eget neque efficitur sollicitudin id vitae nulla. Vivamus mi erat, porttitor ac magna in, vehicula rutrum turpis. Sed porta non nunc a malesuada. Cras et auctor purus.</p>",
		"cover": {
			"data": {
				"attributes": {
					"width": 1920,
					"height": 1280,
					"url": "/jason-leung-t5RYxTDfqqU-unsplash.jpg",
				}
			}
		},
	},
]